var express = require('express');
var app = express();
var cors = require('cors');
app.use(cors());
var cagnotteController = require('./cagnotte/cagnotteController');
app.use('/cagnotte', cagnotteController);
var cagnotteController = require('./cagnotte/cagnotteController');
app.use('/cagnotte', cagnotteController);
var adherentController = require('./adherent/adherentController');
app.use('/adherent', adherentController);
var articleController = require('./article/articleController');
app.use('/article', articleController);
var articleController = require('./article/articleController');
app.use('/article', articleController);
var upload=require('./upload/upload');
app.use('/upload',upload);
var emailing=require('./emailing/emailing');
app.use('/emailing',emailing);
module.exports = app;
